language: node_js
node_js:
  - "7"
defaulbefore_script: 
  - npm install
  - npm install cypress --save-dev
script: cypress run

notifications:
  slack: servicecenterteam:ZbSk5pFAmhGflePGoOU6T88A
  email:
    - eduardo.costa@usereserva.com.br
    
  on_success: always
  on_failure: always 